from api.tests.interview import *
from api.tests.current_user import *
from api.tests.token import *
from api.tests.user import *
from api.tests.article import *
from api.tests.event import *
from api.tests.cart import *
from api.tests.payments import *
from api.tests.activate import *
