---

kind: pipeline
type: docker
name: default

steps:
  - name: build-docker-image
    image: docker:dind
    environment:
      DOCKER_USERNAME:
        from_secret: DOCKER_USERNAME
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
      DOCKER_REGISTRY: registry.mngst.in
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - sleep 5 # give docker enough time to start
      - export IMAGE_NAME=$DRONE_REPO_OWNER/$DRONE_REPO_NAME
      - docker build -t $IMAGE_NAME .
      - echo $DOCKER_PASSWORD > /tmp/docker_password
      - cat /tmp/docker_password | docker login -u $DOCKER_USERNAME --password-stdin $DOCKER_REGISTRY
      - if [[ $DRONE_BRANCH == dev* ]]; then
          export TAG=dev;
        elif [[ $DRONE_BRANCH == main || $DRONE_BRANCH == master ]]; then
          export TAG=latest;
        elif [[ $DRONE_BRANCH == release* ]]; then
          export TAG=staging;
        else
          echo "Not pushing ameba-backend docker image";
        fi
      - echo "Tagging $IMAGE_NAME:$TAG docker image";
      - docker tag $IMAGE_NAME $DOCKER_REGISTRY/$IMAGE_NAME:$TAG;
      - echo "Pushing $IMAGE_NAME:$TAG docker image";
      - docker push $DOCKER_REGISTRY/$IMAGE_NAME:$TAG;

services:
  - name: docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run


volumes:
  - name: dockersock
    temp: {}