---


kind: pipeline
name: default


steps:
- name: test
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - sleep 5 # give docker enough time to start
  - docker-compose build ameba-backend
  - echo "Git branch is:"
  - echo $DRONE_BRANCH"
  - if [ $DRONE_BRANCH == *dev ]; then
      echo "Tagging ameba-backend:dev image";
      docker tag ameba-backend drone:5000/ameba-backend:dev;
      echo "Pushing ameba-backend:dev image";
      docker push ameba-backend drone:5000/ameba-backend:dev;
      echo "Done";
      fi;

services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run


volumes:
- name: dockersock
  temp: {}