---
kind: pipeline
type: docker
name: default

steps:
- name: build-backend-image
  image: docker
  commands:
  - docker build -t ameba/backend .
  volumes:
  - /var/run/docker.sock: /var/run/docker.sock

