version: '3.8'


services:
  ameba-backend:
    build: .
    image: ameba-backend
    command: "python manage.py runserver 0.0.0.0:8000"
    working_dir: /home/ameba/dev_app
    volumes:
      - .:/home/ameba/dev_app
    environment:
      - PYTHONUNBUFFERED=1
      - PUID=$PUID
      - PGID=$PGID
      - POSTGRES_HOST=ameba-db
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DJANGO_SECRET=$DJANGO_SECRET
      - EMAIL_BACKEND=$EMAIL_BACKEND
      - HOST_NAME=$HOST_NAME
      - FE_MEMBERSHIP_CARD_PATH=$FE_MEMBERSHIP_CARD_PATH
      - ACCESS_TOKEN_LIFETIME=$ACCESS_TOKEN_LIFETIME
      - DEFAULT_FROM_EMAIL=$DEFAULT_FROM_EMAIL
      - DEBUG=$DEBUG
    ports:
      - "8000:8000"
    depends_on:
      - ameba-db

  ameba-db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
