
volumes:
  ameba-db-data:
    

services:
  ameba-backend:
    build: .
    image: ameba-backend
    command: "python -m debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000"
    working_dir: /home/ameba/dev_app
    volumes:
      - .:/home/ameba/dev_app
    env_file:
      - .env
    ports:
      - "8000:8000"
      - "5678:5678"
    depends_on:
      - ameba-db
      - ameba-redis

  ameba-db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: ameba-db
    restart: always
    volumes:
      - ameba-db-data:/var/lib/postgresql/data


  ameba-redis:
    image: redis:alpine
    container_name: ameba-redis
    restart: always
    ports:
      - "6379:6379"
