"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from envs import env
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG", False, var_type='boolean')


class MissingSecretKey(Exception):
    pass


def raise_debug():
    raise MissingSecretKey


# SECURITY WARNING: keep the secret key used in production secret!
DEV_SECRET_KEY = 'f!e(2rsmnoiyy@+#s$&lg-m7xp3@-+8fveja$plau=ir--13f('


SECRET_KEY = env(
    "DJANGO_SECRET",
    DEBUG and DEV_SECRET_KEY or raise_debug(),
    var_type='string'
)


ALLOWED_HOSTS = []


# Auth User
AUTH_USER_MODEL = 'api.User'


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'drf_yasg',
    'api.apps.ApiConfig',
    'trumbowyg',
    'location_field.apps.DefaultConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('POSTGRES_DB', 'postgres', 'string'),
        'HOST': env('POSTGRES_HOST', 'db', 'string'),
        'PASSWORD': env('POSTGRES_PASSWORD', 'postgres', 'string'),
        'USER': env('POSTGRES_USER', 'postgres', 'string')
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = 'static/'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONOpenAPIRenderer',
    )
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

MEDIA_ROOT = 'media/'
MEDIA_URL = 'media/'


LOCATION_FIELD = {
    'map.provider': 'openstreetmap',
    'search.provider': 'google',
    'provider.openstreetmap.max_zoom': 18,
}

# EMAIL CONFIG

ACTIVATION_URL = 'activate/{token}/'
EMAIL_BACKEND = env(
    'EMAIL_BACKEND',
    'django.core.mail.backends.smtp.EmailBackend',
    var_type='string'
)

DEFAULT_FROM_EMAIL = 'noreply@ameba.cat'
EMAIL_HOST = env("EMAIL_HOST", '', var_type='string')
EMAIL_HOST_USER = env("EMAIL_HOST_USER", '', var_type='string')
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", '', var_type='string')
EMAIL_PORT = env("EMAIL_PORT", 465, var_type='integer')
EMAIL_USE_SSL = env("EMAIL_USE_SSL", True, var_type='boolean')
PROFILE_VERSION = 8


# STRIPE
STRIPE_TEST_SECRET_KEY = (
    "sk_test_51IGkXjHRg08Ncmk70pYqW"
    "gCE2CR5F02DL1MSRpXq7kC7DUEXOLv"
    "x14qNX1oOe3J4aqKecKWkom8fbAEQQ"
    "RWR3vfp00AOrsyzRW"
)
STRIPE_TEST_PUBLIC_KEY = (
    "pk_test_51IGkXjHRg08Ncmk7fPlbb"
    "9DfTF5f7ckXBKiR4g01euLgXs04Cqm"
    "gBPOQuqQfOhc6aj9mzsYE1oiQ3TFjH"
    "H9Hv3Mj00GNyG9sep"
)

STRIPE_SECRET = env("STRIPE_SECRET", STRIPE_TEST_SECRET_KEY, var_type='string')
STRIPE_PUBLIC = env("STRIPE_PUBLIC", STRIPE_TEST_PUBLIC_KEY, var_type='string')
