# Generated by Django 3.1.3 on 2020-11-10 19:50
import logging

from django.contrib.auth.models import Group, Permission
from django.db import models, migrations


logger = logging.getLogger(__name__)


def add_group_permissions():
    # Standard user
    group, created = Group.objects.get_or_create(name='standard_user')
    if created:
        # group.permissions.add(can_read_campaign)
        logger.info('read_only_user Group created')

    # Member user
    group, created = Group.objects.get_or_create(name='member_user')
    if created:
        # group.permissions.add(can_edit_users)
        logger.info('standard_user Group created')

    # Admin user
    group, created = Group.objects.get_or_create(name='admin_user')
    if created:
        # group.permissions.add(can_edit_campaign, can_edit_users)
        logger.info('admin_user Group created')


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        # migrations.RunPython(add_group_permissions),
    ]
