# Generated by Django 3.1.3 on 2020-11-10 19:50
import logging

from django.contrib.auth.models import Group, Permission
from django.db import models, migrations


logger = logging.getLogger(__name__)


user_groups = {
    'visitor': {
        'permissions': []
    },
    'web_user': {
        'permissions': []
    },
    'member': {
        'permissions': []
    },
    'supporter_member': {
        'permissions': []
    }
}


def add_group_permissions():
    for user_group_name in user_groups:
        group, created = Group.objects.get_or_create(name=user_group_name)
        if created:
            for permission in user_groups[user_group_name]['permissions']:
                group.permissions.add(permission)
                logger.info(f'{user_group_name} Group created')


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        # migrations.RunPython(add_group_permissions),
    ]
