# Generated by Django 3.1.6 on 2021-05-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=120, unique=True)),
                ('is_test', models.BooleanField(default=True)),
            ],
        ),
    ]
