# Generated by Django 3.1.4 on 2020-12-20 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201218_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='artistic_name',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='contact_name',
            new_name='name',
        ),
    ]
