# Generated by Django 3.1.4 on 2020-12-20 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201220_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='member',
            new_name='number',
        ),
    ]
