# Generated by Django 3.1.5 on 2021-01-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_member_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('biography', models.TextField(max_length=2500)),
                ('images', models.ManyToManyField(blank=True, to='api.Image')),
            ],
        ),
    ]
