# Generated by Django 3.1.4 on 2020-12-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201220_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='contact',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AlterField(
            model_name='artist',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
