# Generated by Django 3.1.5 on 2021-01-30 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_answer_interview_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.item')),
            ],
            bases=('api.item',),
        ),
        migrations.CreateModel(
            name='ArticleSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=3)),
                ('genre', models.CharField(blank=True, choices=[('unisex', 'unisex'), ('men', 'men'), ('women', 'women')], max_length=6)),
                ('stock', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='api.article')),
            ],
        ),
    ]
