# Generated by Django 3.1.5 on 2021-01-16 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_answer_interview_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.item')),
            ],
            bases=('api.item',),
        ),
        migrations.CreateModel(
            name='ArticleVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('stock', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('image', models.ManyToManyField(blank=True, to='api.Image')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='variants', to='api.article')),
            ],
        ),
    ]
