# Generated by Django 3.1.6 on 2021-05-27 17:06

import api.models.member
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('number', models.IntegerField(default=api.models.member.get_default_number, primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField(default=365)),
                ('starts', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires', models.DateTimeField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='api.member')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='memberships', to='api.subscription')),
            ],
        ),
    ]
