# Generated by Django 3.1.5 on 2021-01-16 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0007_article_articlevariant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('value', models.IntegerField(verbose_name='Value (%)')),
                ('need_code', models.BooleanField()),
                ('number_of_uses', models.IntegerField()),
                ('groups', models.ManyToManyField(to='auth.Group')),
                ('items', models.ManyToManyField(related_name='discounts', to='api.Item')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.discount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('days_period', models.IntegerField(blank=True, default=30)),
                ('is_expired', models.BooleanField(default=False)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_discounts', to='api.discount')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='discount',
            name='usages',
            field=models.ManyToManyField(related_name='used_discounts', through='api.DiscountUsage', to=settings.AUTH_USER_MODEL),
        ),
    ]
