# Generated by Django 3.1.4 on 2020-12-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_discount_item_itemimage_itemtags_itemvariant_itemvariantimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvariant',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='ItemVariantImage',
        ),
    ]
