# Generated by Django 3.1.4 on 2020-12-30 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201230_1109'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemTags',
            new_name='ItemTag',
        ),
    ]
