# Generated by Django 3.1.4 on 2020-12-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201230_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
