# Generated by Django 3.1.5 on 2021-01-16 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210116_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.item')),
                ('datetime', models.DateTimeField()),
                ('address', models.CharField(max_length=255)),
                ('artists', models.ManyToManyField(blank=True, related_name='events', to='api.Artist')),
            ],
            bases=('api.item',),
        ),
    ]
