# Generated by Django 3.1.6 on 2021-05-27 17:07

import api.models.discount
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0010_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('checkout_details', models.JSONField(blank=True, null=True)),
                ('checkout_hash', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('value', models.IntegerField(verbose_name='Value (%)')),
                ('need_code', models.BooleanField()),
                ('number_of_uses', models.IntegerField()),
                ('groups', models.ManyToManyField(to='auth.Group')),
                ('items', models.ManyToManyField(related_name='discounts', to='api.Item')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.discount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('code', models.CharField(default=api.models.discount.get_random_code, max_length=6, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('days_period', models.IntegerField(blank=True, default=30)),
                ('is_expired', models.BooleanField(default=False)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_discounts', to='api.discount')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='discount',
            name='usages',
            field=models.ManyToManyField(related_name='used_discounts', through='api.DiscountUsage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cart')),
                ('item_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.itemvariant')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.discountcode'),
        ),
        migrations.AddField(
            model_name='cart',
            name='item_variants',
            field=models.ManyToManyField(through='api.CartItems', to='api.ItemVariant'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
