# Generated by Django 3.1.4 on 2020-12-31 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0010_auto_20201230_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('days_period', models.IntegerField(blank=True, default=30)),
                ('is_expired', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='discount',
            old_name='articles',
            new_name='items',
        ),
        migrations.AddField(
            model_name='discount',
            name='groups',
            field=models.ManyToManyField(to='auth.Group'),
        ),
        migrations.AddField(
            model_name='discount',
            name='name',
            field=models.CharField(default='Descuento básico', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount',
            name='need_code',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount',
            name='number_of_uses',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('article', 'Article'), ('subscription', 'Subscription'), ('event', 'Event')], default='article', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='ItemTag',
        ),
        migrations.AddField(
            model_name='discountcode',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_discounts', to='api.discount'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
