# Generated by Django 3.1.5 on 2021-01-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210116_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='images',
            field=models.ManyToManyField(blank=True, to='api.Image'),
        ),
    ]
