# Generated by Django 3.1.4 on 2020-12-31 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20201231_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.IntegerField(verbose_name='Value (%)'),
        ),
        migrations.CreateModel(
            name='DiscountUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.discount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='discount',
            name='usages',
            field=models.ManyToManyField(related_name='used_discounts', through='api.DiscountUsage', to=settings.AUTH_USER_MODEL),
        ),
    ]
