# Generated by Django 3.1.6 on 2021-05-27 17:08

import api.models.subscriber
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_event_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('mailing_lists', models.ManyToManyField(default=api.models.subscriber.default_mailing_lists, related_name='subscribers', to='api.MailingList')),
            ],
        ),
    ]
