# Generated by Django 3.1.4 on 2021-01-03 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20201231_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('introduction', models.TextField(max_length=2000)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='artists')),
            ],
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(upload_to='items'),
        ),
        migrations.AlterField(
            model_name='itemvariant',
            name='image',
            field=models.ImageField(blank=True, upload_to='items'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='answers', to='api.interview', verbose_name='artist'),
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
