# Generated by Django 3.1.6 on 2021-08-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='text_ca_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='text_en_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='text_es_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='biography_ca_es',
            field=models.TextField(max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='biography_en_es',
            field=models.TextField(max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='biography_es_es',
            field=models.TextField(max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='introduction_ca_es',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='introduction_en_es',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='introduction_es_es',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='title_ca_es',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='title_en_es',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='title_es_es',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='description_ca_es',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='description_en_es',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='description_es_es',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='name_ca_es',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='item',
            name='name_en_es',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='item',
            name='name_es_es',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='benefits_ca_es',
            field=models.TextField(default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='benefits_en_es',
            field=models.TextField(default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='benefits_es_es',
            field=models.TextField(default='', max_length=1000, null=True),
        ),
    ]
