# Generated by Django 3.1.5 on 2021-01-25 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210117_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.item')),
                ('benefits', models.TextField(max_length=1000)),
            ],
            bases=('api.item',),
        ),
    ]
