# Generated by Django 3.1.5 on 2021-01-26 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=3)),
                ('genre', models.CharField(blank=True, choices=[('unisex', 'unisex'), ('men', 'men'), ('women', 'women')], max_length=6)),
                ('stock', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sizes', to='api.article')),
            ],
        ),
        migrations.DeleteModel(
            name='ArticleVariant',
        ),
    ]
