# Generated by Django 3.1.4 on 2021-01-03 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210103_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='artist',
        ),
        migrations.AddField(
            model_name='answer',
            name='interview',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='answers', to='api.interview', verbose_name='interview'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interview',
            name='image',
            field=models.ImageField(upload_to='interviews'),
        ),
    ]
