# Generated by Django 3.1.6 on 2021-02-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210206_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
