# Generated by Django 3.1.6 on 2021-04-25 10:37

import api.models.subscriber
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_artistmediaurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=120, unique=True)),
                ('is_test', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('mailing_lists', models.ManyToManyField(default=api.models.subscriber.default_mailing_lists, related_name='subscribers', to='api.MailingList')),
            ],
        ),
    ]
