# Generated by Django 3.1.6 on 2021-02-12 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210206_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='amount',
        ),
    ]
