# Generated by Django 3.1.5 on 2021-01-26 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210126_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlesize',
            old_name='item',
            new_name='article',
        ),
    ]
