# Generated by Django 3.1.6 on 2021-04-26 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_mailinglist_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleAttributeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=1000)),
                ('images', models.ManyToManyField(to='api.Image')),
            ],
        ),
        migrations.DeleteModel(
            name='ArticleSize',
        ),
        migrations.AddField(
            model_name='articleattribute',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.articleattributetype'),
        ),
        migrations.AddField(
            model_name='article',
            name='attributes',
            field=models.ManyToManyField(to='api.ArticleAttribute'),
        ),
        migrations.AddField(
            model_name='article',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='api.articlefamily'),
            preserve_default=False,
        ),
    ]
