# Generated by Django 3.1.6 on 2021-02-12 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_checkout_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='id',
        ),
        migrations.AlterField(
            model_name='checkout',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.cart'),
        ),
    ]
