# Generated by Django 3.1.6 on 2021-02-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210212_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='checkout_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
