# Generated by Django 3.1.6 on 2021-04-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.AddField(
            model_name='itemvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=8),
            preserve_default=False,
        ),
    ]
