# Generated by Django 3.1.6 on 2021-02-15 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210213_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='chart_record',
            new_name='cart_record',
        ),
    ]
