# Generated by Django 3.1.5 on 2021-01-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20210115_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='raw',
            field=models.CharField(max_length=255),
        ),
    ]
