# Generated by Django 3.1.6 on 2021-02-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20210215_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.AlterField(
            model_name='payment',
            name='details',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
