# Generated by Django 3.1.6 on 2021-02-17 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20210216_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='expires',
        ),
        migrations.AddField(
            model_name='membership',
            name='subscription',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='api.subscription'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='api.user'),
            preserve_default=False,
        ),
    ]
