# Generated by Django 3.1.5 on 2021-01-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20210115_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(default='Barcelona, Spain', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='coordinates',
            field=models.CharField(default='0, 0', max_length=255),
            preserve_default=False,
        ),
    ]
