# Generated by Django 3.1.6 on 2021-05-01 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20210429_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='item',
        ),
        migrations.AddField(
            model_name='cart',
            name='item_variants',
            field=models.ManyToManyField(through='api.CartItems', to='api.ItemVariant'),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='item_variant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.itemvariant'),
            preserve_default=False,
        ),
    ]
