# Generated by Django 3.1.6 on 2021-08-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('es-es', 'Español'), ('ca-es', 'Catalá'), ('en-es', 'English')], max_length=7, null=True),
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
