# Generated by Django 3.1.6 on 2021-08-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20210811_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('es-es', 'Español'), ('ca-es', 'Catalá'), ('en-es', 'English')], default='', max_length=7),
            preserve_default=False,
        ),
    ]
