# Generated by Django 3.1.6 on 2021-05-06 17:12

import api.models.member
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20210506_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='number',
            field=models.IntegerField(default=api.models.member.get_default_number, primary_key=True, serialize=False),
        ),
    ]
