# Generated by Django 3.1.5 on 2021-01-15 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20210115_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_expired',
        ),
        migrations.RemoveField(
            model_name='item',
            name='type',
        ),
    ]
