# Generated by Django 3.1.6 on 2021-05-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20210506_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='introduction',
            field=models.TextField(blank=True, max_length=2500),
        ),
    ]
