# Generated by Django 3.1.5 on 2021-01-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20210115_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_event',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
