# Generated by Django 3.1.6 on 2021-05-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_interview_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='image',
            field=models.ImageField(blank=True, upload_to='interviews'),
        ),
    ]
