# Generated by Django 3.1.5 on 2021-01-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='date',
        ),
        migrations.AlterField(
            model_name='item',
            name='is_event',
            field=models.BooleanField(default=False),
        ),
    ]
