# Generated by Django 3.1.6 on 2021-05-10 18:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_interview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='starts',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
