# Generated by Django 3.1.6 on 2021-08-24 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20210824_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='type',
            new_name='tag',
        ),
    ]
