# Generated by Django 3.1.5 on 2021-01-15 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20210115_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='item',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_event',
        ),
        migrations.AddField(
            model_name='item',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='api.event'),
        ),
    ]
