# Generated by Django 3.1.6 on 2021-05-10 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0028_itemvariant_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemvariant',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='itemvariant',
            name='group',
        ),
        migrations.AddField(
            model_name='subscription',
            name='benefits',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='subscription',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
    ]
