# Generated by Django 3.1.5 on 2021-01-15 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20210115_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='', upload_to='events'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='api.event', verbose_name='Event data'),
        ),
    ]
