# Generated by Django 3.1.6 on 2021-08-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20210824_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='tags',
            field=models.ManyToManyField(blank=True, to='api.ArtistTag'),
        ),
    ]
