# Generated by Django 3.1.6 on 2021-05-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20210510_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='checkout_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
