# Generated by Django 3.1.5 on 2021-01-16 09:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20210115_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='events', to='api.Artist'),
        ),
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='interested',
            field=models.ManyToManyField(blank=True, related_name='favorite_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
