# Generated by Django 3.1.6 on 2021-05-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_cart_checkout_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cover',
            name='image',
        ),
        migrations.AddField(
            model_name='cover',
            name='file',
            field=models.FileField(default=0, upload_to='covers'),
            preserve_default=False,
        ),
    ]
