# Generated by Django 3.1.6 on 2021-08-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20210824_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisttag',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='artisttag',
            name='name_ca',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='artisttag',
            name='name_en',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='artisttag',
            name='name_es',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
