# Generated by Django 3.1.5 on 2021-01-16 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20210116_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.item')),
            ],
            bases=('api.item',),
        ),
        migrations.CreateModel(
            name='ArticleVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('stock', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.RemoveField(
            model_name='itemvariant',
            name='item',
        ),
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created',
        ),
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.RemoveField(
            model_name='event',
            name='interested',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_closed',
        ),
        migrations.RemoveField(
            model_name='event',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='item',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='item_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='acquired_by',
            field=models.ManyToManyField(blank=True, related_name='acquired_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ItemImage',
        ),
        migrations.DeleteModel(
            name='ItemVariant',
        ),
        migrations.AddField(
            model_name='articlevariant',
            name='image',
            field=models.ManyToManyField(blank=True, to='api.Image'),
        ),
        migrations.AddField(
            model_name='articlevariant',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='variants', to='api.article'),
        ),
        migrations.AddField(
            model_name='item',
            name='images',
            field=models.ManyToManyField(to='api.Image'),
        ),
    ]
