# Generated by Django 3.1.6 on 2021-08-25 15:36

import api.models.discount
import api.models.member
import api.models.subscriber
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0031_auto_20210824_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About', 'verbose_name_plural': 'Abouts'},
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Respuesta', 'verbose_name_plural': 'Respuestas'},
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'Artist', 'verbose_name_plural': 'Artists'},
        ),
        migrations.AlterModelOptions(
            name='artistmediaurl',
            options={'verbose_name': 'Artist media url', 'verbose_name_plural': 'Artist media urls'},
        ),
        migrations.AlterModelOptions(
            name='artisttag',
            options={'verbose_name': 'Artist tag', 'verbose_name_plural': 'Artist tags'},
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'cart'},
        ),
        migrations.AlterModelOptions(
            name='cartitems',
            options={'verbose_name': 'Cart items', 'verbose_name_plural': 'Cart items'},
        ),
        migrations.AlterModelOptions(
            name='cover',
            options={'verbose_name': 'Cover', 'verbose_name_plural': 'Covers'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'Discount', 'verbose_name_plural': 'Discounts'},
        ),
        migrations.AlterModelOptions(
            name='discountcode',
            options={'verbose_name': 'Discount code', 'verbose_name_plural': 'Discount codes'},
        ),
        migrations.AlterModelOptions(
            name='discountusage',
            options={'verbose_name': 'Discount usage', 'verbose_name_plural': 'Discount usages'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='eventtype',
            options={'verbose_name': 'Event type', 'verbose_name_plural': 'Event types'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='interview',
            options={'verbose_name': 'Entrevista', 'verbose_name_plural': 'Entrevistas'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Ítem', 'verbose_name_plural': 'Ítems'},
        ),
        migrations.AlterModelOptions(
            name='itemattribute',
            options={'verbose_name': 'Atributo de ítem', 'verbose_name_plural': 'Atributos de ítem'},
        ),
        migrations.AlterModelOptions(
            name='itemattributetype',
            options={'verbose_name': 'Tipo de atributo de ítem', 'verbose_name_plural': 'Tipos de atributos de ítem'},
        ),
        migrations.AlterModelOptions(
            name='itemvariant',
            options={'verbose_name': 'Variante de ítem', 'verbose_name_plural': 'Variantes de ítem'},
        ),
        migrations.AlterModelOptions(
            name='mailinglist',
            options={'verbose_name': 'Lista de emails', 'verbose_name_plural': 'Listas de emails'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Socio', 'verbose_name_plural': 'Socios'},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'Membresía', 'verbose_name_plural': 'Membresías'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Pregunta', 'verbose_name_plural': 'Preguntas'},
        ),
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Subscriptor', 'verbose_name_plural': 'Subscriptores'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Subscripción', 'verbose_name_plural': 'Subscripciones'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='about',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='about',
            name='is_active',
            field=models.BooleanField(verbose_name='is_active'),
        ),
        migrations.AlterField(
            model_name='about',
            name='text',
            field=models.TextField(verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='about',
            name='text_ca',
            field=models.TextField(null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='about',
            name='text_en',
            field=models.TextField(null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='about',
            name='text_es',
            field=models.TextField(null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='about',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(max_length=1000, verbose_name='respuesta'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.interview', verbose_name='entrevista'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question', verbose_name='pregunta'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='biography',
            field=models.TextField(max_length=2500, verbose_name='biography'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='biography_ca',
            field=models.TextField(max_length=2500, null=True, verbose_name='biography'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='biography_en',
            field=models.TextField(max_length=2500, null=True, verbose_name='biography'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='biography_es',
            field=models.TextField(max_length=2500, null=True, verbose_name='biography'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='images',
            field=models.ManyToManyField(blank=True, to='api.Image', verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='tags',
            field=models.ManyToManyField(blank=True, to='api.ArtistTag', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='artistmediaurl',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_urls', to='api.artist', verbose_name='artist'),
        ),
        migrations.AlterField(
            model_name='artistmediaurl',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='artistmediaurl',
            name='url',
            field=models.URLField(verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='artisttag',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='artisttag',
            name='name_ca',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='artisttag',
            name='name_en',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='artisttag',
            name='name_es',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='checkout_details',
            field=models.JSONField(blank=True, null=True, verbose_name='checkout details'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='checkout_hash',
            field=models.CharField(blank=True, max_length=128, verbose_name='checkout hash'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.discountcode', verbose_name='discount code'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='item_variants',
            field=models.ManyToManyField(through='api.CartItems', to='api.ItemVariant', verbose_name='item variants'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_cart', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cart', verbose_name='cart'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='item_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.itemvariant', verbose_name='item variant'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='file',
            field=models.FileField(upload_to='covers', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='index',
            field=models.IntegerField(verbose_name='index'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='is_active',
            field=models.BooleanField(verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='groups',
            field=models.ManyToManyField(to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='items',
            field=models.ManyToManyField(related_name='discounts', to='api.Item', verbose_name='items'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.CharField(max_length=25, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='need_code',
            field=models.BooleanField(verbose_name='need code'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='number_of_uses',
            field=models.IntegerField(verbose_name='number of uses'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='usages',
            field=models.ManyToManyField(related_name='used_discounts', through='api.DiscountUsage', to=settings.AUTH_USER_MODEL, verbose_name='usages'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(default=api.models.discount.get_random_code, max_length=6, primary_key=True, serialize=False, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='days_period',
            field=models.IntegerField(blank=True, default=30, verbose_name='days period'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_discounts', to='api.discount', verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='is_expired',
            field=models.BooleanField(default=False, verbose_name='is expired'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='discountusage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='discountusage',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.discount', verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='discountusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(max_length=255, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='event',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='events', to='api.Artist', verbose_name='artists'),
        ),
        migrations.AlterField(
            model_name='event',
            name='datetime',
            field=models.DateTimeField(verbose_name='datetime'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.eventtype', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='name',
            field=models.CharField(max_length=20, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='name_ca',
            field=models.CharField(max_length=20, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='name_en',
            field=models.CharField(max_length=20, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='name_es',
            field=models.CharField(max_length=20, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.artist', verbose_name='artista'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='image',
            field=models.ImageField(blank=True, upload_to='interviews', verbose_name='imágen'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='introduction',
            field=models.TextField(blank=True, max_length=2500, verbose_name='introducción'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='introduction_ca',
            field=models.TextField(blank=True, max_length=2500, null=True, verbose_name='introducción'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='introduction_en',
            field=models.TextField(blank=True, max_length=2500, null=True, verbose_name='introducción'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='introduction_es',
            field=models.TextField(blank=True, max_length=2500, null=True, verbose_name='introducción'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='title',
            field=models.CharField(max_length=55, verbose_name='titulo'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='title_ca',
            field=models.CharField(max_length=55, null=True, verbose_name='titulo'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='title_en',
            field=models.CharField(max_length=55, null=True, verbose_name='titulo'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='title_es',
            field=models.CharField(max_length=55, null=True, verbose_name='titulo'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado en'),
        ),
        migrations.AlterField(
            model_name='item',
            name='acquired_by',
            field=models.ManyToManyField(blank=True, related_name='acquired_items', to=settings.AUTH_USER_MODEL, verbose_name='adquirido por'),
        ),
        migrations.AlterField(
            model_name='item',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description_ca',
            field=models.TextField(max_length=1000, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description_en',
            field=models.TextField(max_length=1000, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description_es',
            field=models.TextField(max_length=1000, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='item',
            name='images',
            field=models.ManyToManyField(to='api.Image', verbose_name='imágenes'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name_ca',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name_es',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='item',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_items', to=settings.AUTH_USER_MODEL, verbose_name='guardado por'),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado en'),
        ),
        migrations.AlterField(
            model_name='itemattribute',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.itemattributetype', verbose_name='atributo'),
        ),
        migrations.AlterField(
            model_name='itemattribute',
            name='value',
            field=models.CharField(max_length=15, verbose_name='valor'),
        ),
        migrations.AlterField(
            model_name='itemvariant',
            name='attributes',
            field=models.ManyToManyField(to='api.ItemAttribute', verbose_name='atributo'),
        ),
        migrations.AlterField(
            model_name='itemvariant',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='api.item', verbose_name='ítem'),
        ),
        migrations.AlterField(
            model_name='itemvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='precio'),
        ),
        migrations.AlterField(
            model_name='mailinglist',
            name='address',
            field=models.CharField(max_length=120, unique=True, verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='mailinglist',
            name='is_test',
            field=models.BooleanField(default=True, verbose_name='de prueba'),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='member',
            name='number',
            field=models.IntegerField(default=api.models.member.get_default_number, primary_key=True, serialize=False, verbose_name='número'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(max_length=10, verbose_name='número de teléfono'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='duration',
            field=models.IntegerField(default=365, verbose_name='duración'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='expires',
            field=models.DateTimeField(blank=True, verbose_name='caduca'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='api.member', verbose_name='socio'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='starts',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='comienza'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='memberships', to='api.subscription', verbose_name='subscripción'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cart_record',
            field=models.JSONField(verbose_name='registro de carrito'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='details',
            field=models.JSONField(verbose_name='detalles'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='por defecto'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(max_length=200, verbose_name='pregunta'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='mailing_lists',
            field=models.ManyToManyField(default=api.models.subscriber.default_mailing_lists, related_name='subscribers', to='api.MailingList', verbose_name='listas de emails'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='benefits',
            field=models.TextField(default='', max_length=1000, verbose_name='beneficios'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='benefits_ca',
            field=models.TextField(default='', max_length=1000, null=True, verbose_name='beneficios'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='benefits_en',
            field=models.TextField(default='', max_length=1000, null=True, verbose_name='beneficios'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='benefits_es',
            field=models.TextField(default='', max_length=1000, null=True, verbose_name='beneficios'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group', verbose_name='grupo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('es', 'Español'), ('ca', 'Catalá'), ('en', 'English')], max_length=7, verbose_name='language'),
        ),
    ]
