# Generated by Django 3.1.6 on 2021-05-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='state',
            field=models.CharField(blank=True, choices=[('checkout_failed', 'checkout_failed'), ('payment_pending', 'payment_pending'), ('payment_failed', 'payment_failed')], max_length=20),
        ),
    ]
