# Generated by Django 3.1.6 on 2021-08-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20210826_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='biography_en',
        ),
        migrations.RemoveField(
            model_name='artisttag',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='introduction_en',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='item',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='itemattributetype',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='benefits_en',
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('es', 'Español'), ('ca', 'Catalá')], max_length=7, verbose_name='language'),
        ),
    ]
