# Generated by Django 3.1.6 on 2021-05-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_cart_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='state',
            field=models.CharField(blank=True, choices=[('checkout_intent', 'checkout_intent'), ('checkout_ready', 'checkout_ready'), ('payment_failed', 'payment_failed')], max_length=20),
        ),
    ]
