# Generated by Django 3.1.6 on 2021-05-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20210517_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='state',
            field=models.CharField(blank=True, choices=[('cart_co_needs_login', 'cart_co_needs_login'), ('memb_co_needs_login', 'memb_co_needs_login'), ('cart_co_ready', 'cart_co_ready'), ('memb_co_needs_profile', 'memb_co_needs_profile'), ('memb_co_ready', 'memb_co_ready'), ('co_finished_delete_pending', 'co_finished_delete_pending')], max_length=30),
        ),
    ]
