# Generated by Django 3.1.6 on 2021-09-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20210827_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
