# Generated by Django 3.1.6 on 2021-09-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_interview_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='is_ameba_dj',
            field=models.BooleanField(default=False),
        ),
    ]
