# Generated by Django 3.1.6 on 2021-05-21 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20210520_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='state',
        ),
    ]
