# Generated by Django 3.2.7 on 2021-09-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_artist_is_ameba_dj'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
