# Generated by Django 3.2.8 on 2021-10-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_artist_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='auto_renew',
            field=models.BooleanField(default=True),
        ),
    ]
