# Generated by Django 3.2.8 on 2021-10-29 13:30

from django.db import migrations
import localflavor.es.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_membership_auto_renew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='address',
        ),
        migrations.AddField(
            model_name='member',
            name='identity_card',
            field=localflavor.es.models.ESIdentityCardNumberField(default='12345678A', max_length=9, verbose_name='dni/nie'),
            preserve_default=False,
        ),
    ]
