# Generated by Django 3.2.8 on 2021-10-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20211029_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistmediaurl',
            name='embedded',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
