# Generated by Django 3.2.8 on 2021-11-01 11:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_artistmediaurl_embedded'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='qr_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
