# Generated by Django 3.2.9 on 2021-11-02 19:43

import api.models.member
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_member_qr_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='qr_date',
            field=models.CharField(default=api.models.member.get_default_qr_date, max_length=14),
        ),
    ]
