# Generated by Django 3.2.9 on 2021-11-10 19:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_member_qr_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='acquired_by',
        ),
        migrations.AddField(
            model_name='itemvariant',
            name='acquired_by',
            field=models.ManyToManyField(blank=True, related_name='item_variants', to=settings.AUTH_USER_MODEL, verbose_name='adquirido por'),
        ),
    ]
