# Generated by Django 3.2.9 on 2021-11-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20211110_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvariant',
            name='recurrence',
            field=models.CharField(blank=True, choices=[('year', 'year'), ('minute', 'minute')], default=None, max_length=10, null=True),
        ),
    ]
