# Generated by Django 3.2 on 2021-12-12 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_itemvariant_recurrence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='details',
        ),
        migrations.AddField(
            model_name='payment',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.cart'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.JSONField(default={'amount_due': 1000, 'status': 'paid'}, verbose_name='invoice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice_id',
            field=models.CharField(default='in_xxxxxxxxxxxxxxxxxxxxxxxx', max_length=64),
            preserve_default=False,
        ),
    ]
