# Generated by Django 3.2 on 2022-01-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_payment_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='invoice',
        ),
        migrations.AddField(
            model_name='payment',
            name='cart_hash',
            field=models.CharField(blank=True, max_length=128, verbose_name='cart checkout hash'),
        ),
        migrations.AddField(
            model_name='payment',
            name='details',
            field=models.JSONField(null=True, verbose_name='invoice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='item_variants',
            field=models.ManyToManyField(related_name='payments', to='api.ItemVariant'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_intent_id',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice_id',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
