# Generated by Django 3.2 on 2022-01-13 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20220112_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='cart_hash',
        ),
    ]
