# Generated by Django 3.2 on 2022-01-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20220115_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cart_record',
            field=models.JSONField(null=True, verbose_name='registro de carrito'),
        ),
    ]
