# Generated by Django 3.2 on 2022-01-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20220116_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='number_of_uses',
        ),
        migrations.AddField(
            model_name='discount',
            name='is_single_use',
            field=models.BooleanField(default=True),
        ),
    ]
