# Generated by Django 3.2 on 2022-01-29 17:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Orden', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='Ronda de Sant Pau, 17, 08015 Barcelona (https://goo.gl/maps/RSAfNpoG8zjhSMNF9)', max_length=1000, verbose_name='dirección'),
        ),
        migrations.AddField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered',
            field=models.BooleanField(default=False, verbose_name='delivered'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ready',
            field=models.BooleanField(default=False, verbose_name='ready'),
        ),
    ]
