# Generated by Django 3.2 on 2022-02-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_auto_20220129_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(max_length=5000, verbose_name='respuesta'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='introduction',
            field=models.TextField(blank=True, max_length=5000, verbose_name='introducción'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='introduction_ca',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='introducción'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='introduction_es',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='introducción'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default='Ronda de Sant Pau, 17, 08015 Barcelona', max_length=1000, verbose_name='dirección'),
        ),
    ]
