# Generated by Django 3.2 on 2022-02-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_auto_20220202_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(max_length=5000, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description_ca',
            field=models.TextField(max_length=5000, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description_es',
            field=models.TextField(max_length=5000, null=True, verbose_name='descripción'),
        ),
    ]
