# Generated by Django 3.2 on 2022-02-27 09:36

import api.models.member
import api.models.subscriber
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_auto_20220202_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='interview',
            options={'verbose_name': 'Interview', 'verbose_name_plural': 'Interviews'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='itemattribute',
            options={'verbose_name': 'Item attribute', 'verbose_name_plural': 'Item attributes'},
        ),
        migrations.AlterModelOptions(
            name='itemattributetype',
            options={'verbose_name': 'Item attribute type', 'verbose_name_plural': 'Item attribute types'},
        ),
        migrations.AlterModelOptions(
            name='itemvariant',
            options={'verbose_name': 'Item variant', 'verbose_name_plural': 'Item variants'},
        ),
        migrations.AlterModelOptions(
            name='mailinglist',
            options={'verbose_name': 'Mailing list', 'verbose_name_plural': 'Mailing lists'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'Membership', 'verbose_name_plural': 'Memberships'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Subscriber', 'verbose_name_plural': 'Subscribers'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Subscription', 'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.AddField(
            model_name='event',
            name='header',
            field=models.CharField(default='Encabezado', max_length=22, verbose_name='header'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(max_length=5000, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.interview', verbose_name='interview'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question', verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.artist', verbose_name='artist'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='image',
            field=models.ImageField(blank=True, upload_to='interviews', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='introduction',
            field=models.TextField(blank=True, max_length=5000, verbose_name='introduction'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='introduction_ca',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='introduction'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='introduction_es',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='introduction'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='item',
            name='images',
            field=models.ManyToManyField(to='api.Image', verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='item',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_items', to=settings.AUTH_USER_MODEL, verbose_name='saved by'),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='itemattribute',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.itemattributetype', verbose_name='attribute'),
        ),
        migrations.AlterField(
            model_name='itemattribute',
            name='value',
            field=models.CharField(max_length=15, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='itemvariant',
            name='acquired_by',
            field=models.ManyToManyField(blank=True, related_name='item_variants', to=settings.AUTH_USER_MODEL, verbose_name='acquired by'),
        ),
        migrations.AlterField(
            model_name='itemvariant',
            name='attributes',
            field=models.ManyToManyField(to='api.ItemAttribute', verbose_name='attributes'),
        ),
        migrations.AlterField(
            model_name='itemvariant',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='api.item', verbose_name='item'),
        ),
        migrations.AlterField(
            model_name='itemvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='itemvariant',
            name='recurrence',
            field=models.CharField(blank=True, choices=[('year', 'year'), ('day', 'day')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mailinglist',
            name='address',
            field=models.CharField(max_length=120, unique=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='mailinglist',
            name='is_test',
            field=models.BooleanField(default=True, verbose_name='is test'),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='apellidos'),
        ),
        migrations.AlterField(
            model_name='member',
            name='number',
            field=models.IntegerField(default=api.models.member.get_default_number, primary_key=True, serialize=False, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(max_length=10, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='duration',
            field=models.IntegerField(default=365, verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='expires',
            field=models.DateTimeField(blank=True, verbose_name='expires'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='api.member', verbose_name='member'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='starts',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='starts'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='memberships', to='api.subscription', verbose_name='subscription'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default='Ronda de Sant Pau, 17, 08015 Barcelona', max_length=1000, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cart_record',
            field=models.JSONField(null=True, verbose_name='cart record'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='is default'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(max_length=2000, verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='mailing_lists',
            field=models.ManyToManyField(default=api.models.subscriber.default_mailing_lists, related_name='subscribers', to='api.MailingList', verbose_name='mailing lists'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='benefits',
            field=models.TextField(default='', max_length=1000, verbose_name='benefits'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='benefits_ca',
            field=models.TextField(default='', max_length=1000, null=True, verbose_name='benefits'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='benefits_es',
            field=models.TextField(default='', max_length=1000, null=True, verbose_name='benefits'),
        ),
    ]
