# Generated by Django 3.2 on 2022-02-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_auto_20220227_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='header_ca',
            field=models.CharField(max_length=22, null=True, verbose_name='header'),
        ),
        migrations.AddField(
            model_name='event',
            name='header_es',
            field=models.CharField(max_length=22, null=True, verbose_name='header'),
        ),
    ]
