# Generated by Django 3.2 on 2022-02-27 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_auto_20220227_0952'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='Manifest',
        ),
        migrations.AlterModelOptions(
            name='manifest',
            options={'verbose_name': 'Manifest', 'verbose_name_plural': 'Manifests'},
        ),
    ]
