# Generated by Django 3.2 on 2022-03-02 21:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_auto_20220227_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvariant',
            name='checked_in',
            field=models.ManyToManyField(blank=True, related_name='checked_in_events', to=settings.AUTH_USER_MODEL, verbose_name='checked in'),
        ),
    ]
