# Generated by Django 3.2 on 2022-03-14 16:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_itemvariant_checked_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='order',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='order'),
            preserve_default=False,
        ),
    ]
