# Generated by Django 3.2 on 2022-03-14 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_item_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='order',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='order'),
        ),
    ]
