# Generated by Django 3.2 on 2022-07-06 20:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_auto_20220706_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
