# Generated by Django 3.2 on 2023-11-13 20:11

import api.models.collaborators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_auto_20231113_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborator',
            name='order',
        ),
        migrations.AddField(
            model_name='collaborator',
            name='position',
            field=models.IntegerField(blank=True, default=api.models.collaborators.get_default_order, null=True, verbose_name='position'),
        ),
    ]
