# Generated by Django 3.2 on 2023-11-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_auto_20231113_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='maps_url',
            field=models.URLField(blank=True, null=True, verbose_name='maps url'),
        ),
    ]
