# Generated by Django 3.2 on 2023-12-07 08:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_event_maps_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicGenres',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Music genre',
                'verbose_name_plural': 'Music genres',
            },
        ),
        migrations.AlterModelOptions(
            name='collaborator',
            options={'verbose_name': 'Collaborator', 'verbose_name_plural': 'Collaborators'},
        ),
        migrations.AddField(
            model_name='member',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='creado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='description',
            field=models.TextField(max_length=2500, null=True, verbose_name='biography'),
        ),
        migrations.AddField(
            model_name='member',
            name='image',
            field=models.ImageField(null=True, upload_to='member_projects', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='member',
            name='project_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='project name'),
        ),
        migrations.AddField(
            model_name='member',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='members', to='api.ArtistTag', verbose_name='tags'),
        ),
        migrations.CreateModel(
            name='MemberMediaUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='url')),
                ('embedded', models.TextField(blank=True, max_length=3000)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_urls', to='api.member', verbose_name='Member media url')),
            ],
            options={
                'verbose_name': 'Member media url',
                'verbose_name_plural': 'Member media urls',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, related_name='members', to='api.MusicGenres', verbose_name='genres'),
        ),
    ]
