# Generated by Django 3.2 on 2023-11-30 20:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_event_maps_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('description', models.TextField(max_length=2500, verbose_name='biography')),
                ('public', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('images', models.ManyToManyField(blank=True, to='api.Image', verbose_name='images')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='api.member', verbose_name='member')),
                ('tags', models.ManyToManyField(blank=True, to='api.ArtistTag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'Member project',
                'verbose_name_plural': 'Member projects',
            },
        ),
        migrations.AlterModelOptions(
            name='collaborator',
            options={'verbose_name': 'Collaborator', 'verbose_name_plural': 'Collaborators'},
        ),
        migrations.CreateModel(
            name='MemberProjectMediaUrl',
            fields=[
                ('artistmediaurl_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.artistmediaurl')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_urls', to='api.memberproject', verbose_name='artist')),
            ],
            options={
                'verbose_name': 'Project media url',
                'verbose_name_plural': 'Project media urls',
            },
            bases=('api.artistmediaurl',),
        ),
    ]
