# Generated by Django 3.2 on 2023-12-06 18:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_event_maps_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProject',
            fields=[
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='project', serialize=False, to='api.member', verbose_name='member')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('description', models.TextField(max_length=2500, verbose_name='biography')),
                ('image', models.ImageField(upload_to='member_projects', verbose_name='image')),
                ('public', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('tags', models.ManyToManyField(blank=True, to='api.ArtistTag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'Member project',
                'verbose_name_plural': 'Member projects',
            },
        ),
        migrations.AlterModelOptions(
            name='collaborator',
            options={'verbose_name': 'Collaborator', 'verbose_name_plural': 'Collaborators'},
        ),
        migrations.CreateModel(
            name='MemberProjectMediaUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='url')),
                ('embedded', models.TextField(blank=True, max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_urls', to='api.memberproject', verbose_name='artist')),
            ],
            options={
                'verbose_name': 'Project media url',
                'verbose_name_plural': 'Project media urls',
            },
        ),
    ]
