# Generated by Django 3.2 on 2023-12-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_auto_20231226_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicgenres',
            name='validated',
            field=models.BooleanField(default=False, verbose_name='validated'),
        ),
    ]
