# Generated by Django 3.2 on 2024-03-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_musicgenres_validated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='members', to='api.MusicGenres', verbose_name='genres'),
        ),
        migrations.AlterField(
            model_name='member',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='members', to='api.ArtistTag', verbose_name='tags'),
        ),
    ]
