# Generated by Django 3.2 on 2024-05-06 07:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_auto_20240430_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='legal/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('position', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Legal Document',
                'verbose_name_plural': 'Legal Documents',
            },
        ),
        migrations.AlterField(
            model_name='itemvariant',
            name='attributes',
            field=models.ManyToManyField(related_name='variants', to='api.ItemAttribute', verbose_name='attributes'),
        ),
        migrations.AlterField(
            model_name='member',
            name='identity_card',
            field=models.CharField(max_length=20, verbose_name='dni/nie'),
        ),
    ]
