# Generated by Django 3.2 on 2025-05-13 08:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_auto_20240506_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('subject', models.TextField(max_length=255, verbose_name='subject')),
                ('subject_es', models.TextField(max_length=255, null=True, verbose_name='subject')),
                ('subject_ca', models.TextField(max_length=255, null=True, verbose_name='subject')),
                ('content', ckeditor.fields.RichTextField(verbose_name='content')),
                ('content_es', ckeditor.fields.RichTextField(null=True, verbose_name='content')),
                ('content_ca', ckeditor.fields.RichTextField(null=True, verbose_name='content')),
                ('base_template', models.CharField(default='generic.html', max_length=50, verbose_name='base template')),
                ('example_context', models.JSONField(verbose_name='example context')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
            },
        ),
        migrations.AlterField(
            model_name='itemvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Usa este campo para indicar el precio del producto o evento.Si es un evento gratuito, introduce el valor 0.', max_digits=8, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='itemvariant',
            name='stock',
            field=models.IntegerField(help_text='Usa este campo para indicar la cantidad de stock disponible.\nSi se trata de un evento, introduce el número de plazas/entradas disponibles.\nSi la gestión del aforo no se realiza a través de la web, introduce -1.\nPor ejemplo, si la entrada es libre hasta completar aforo o si la venta de entradas se gestiona directamente en taquilla.', verbose_name='stock'),
        ),
    ]
