# Generated by Django 3.2 on 2025-07-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_auto_20240506_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Usa este campo para indicar el precio del producto o evento.Si es un evento gratuito, introduce el valor 0.', max_digits=8, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='itemvariant',
            name='stock',
            field=models.IntegerField(help_text='Usa este campo para indicar la cantidad de stock disponible.\nSi se trata de un evento, introduce el número de plazas/entradas disponibles.\nSi la gestión del aforo no se realiza a través de la web, introduce -1.\nPor ejemplo, si la entrada es libre hasta completar aforo o si la venta de entradas se gestiona directamente en taquilla.', verbose_name='stock'),
        ),
    ]
