# Generated by Django 3.2 on 2025-12-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_create_initial_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='number',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='number'),
        ),
    ]
