# Generated by Django 3.2 on 2026-02-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_alter_member_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='number',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='number'),
        ),
    ]
