# Generated by Django 3.2 on 2026-09-14 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_reconcile_artist_tags'),
        ('api', '0080_alter_member_number'),
    ]

    operations = [
    ]
