# Generated by Django 3.2 on 2026-09-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_merge_20260914_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='cart',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('pickup', 'Pickup'), ('shipping', 'Shipping')], max_length=16, verbose_name='delivery method'),
        ),
        migrations.AddField(
            model_name='cart',
            name='pickup_location',
            field=models.CharField(blank=True, choices=[('trama', 'Trama Serigrafia — Carrer de Conca, 13-15, Sant Martí, 08026 Barcelona'), ('merla', 'La Merla (botiga) — Carrer de Sants, 1, Sants-Montjuïc, 08014 Barcelona')], max_length=16, verbose_name='pickup location'),
        ),
        migrations.AddField(
            model_name='cart',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='shipping address'),
        ),
        migrations.AddField(
            model_name='cart',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=255, verbose_name='shipping city'),
        ),
        migrations.AddField(
            model_name='cart',
            name='shipping_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='shipping name'),
        ),
        migrations.AddField(
            model_name='cart',
            name='shipping_postal_code',
            field=models.CharField(blank=True, max_length=16, verbose_name='shipping postal code'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('pickup', 'Pickup'), ('shipping', 'Shipping')], max_length=16, verbose_name='delivery method'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_location',
            field=models.CharField(blank=True, choices=[('trama', 'Trama Serigrafia — Carrer de Conca, 13-15, Sant Martí, 08026 Barcelona'), ('merla', 'La Merla (botiga) — Carrer de Sants, 1, Sants-Montjuïc, 08014 Barcelona')], max_length=16, verbose_name='pickup location'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='shipping address'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=255, verbose_name='shipping city'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='shipping name'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_postal_code',
            field=models.CharField(blank=True, max_length=16, verbose_name='shipping postal code'),
        ),
    ]
