from api.views.token import TokenView
from api.views.user import UserViewSet
from api.views.interview import InterviewViewSet
from api.views.articles import ArticleViewSet
from api.views.cart import CartViewSet
from api.views.event import EventViewSet
from api.views.event import UserSavedEventsViewSet
from api.views.subscription import SubscriptionViewSet
from api.views.activation import my_view
from api.views.version import current_version
