from api.admin.user import UserAdmin
from api.admin.interview import InterviewAdmin
from api.admin.article import ArticleAdmin
from api.admin.discount import DiscountAdmin
from api.admin.cart import CartAdmin
from api.admin.event import EventAdmin
from api.admin.image import ImageAdmin
from api.admin.artist import ArtistAdmin
from api.admin.subscription import SubscriptionAdmin
from api.admin.payment import PaymentAdmin
