name: Build, Test and Push Docker image

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build backend image with docker-compose
        run: docker compose build ameba-backend

      - name: Run tests
        run: docker compose run --rm ameba-backend python manage.py test


      - name: Tag and push image
        if: success()
        run: |
          IMAGE_LOCAL=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep ameba-backend | head -n 1)

          # Etiqueta para GHCR
          docker tag "$IMAGE_LOCAL" ghcr.io/${{ github.repository }}:latest

          # Push
          docker push ghcr.io/${{ github.repository }}:latest
